/* #UPDATED */
/* #CLEARED */
package org.test.webcam.model.domain.entity;

// Generated 07.05.2015 16:26:32 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonProperty;

import org.hibernate.annotations.FetchMode;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.BatchSize;
import org.test.webcam.model.domain.SRel;

import javax.persistence.PreRemove;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RelUserSettings generated by hbm2java, updated by voovee
 */
@JsonIgnoreProperties({
			 
			  "firmid"
			, "firm"
			, "serieskey" 
})
@Entity
@Table(name="rel_user_settings")
public class RelUserSettings extends SRel  {

	private static final long serialVersionUID = 8446813713391411L;

	@JsonProperty("id") private Integer id;
	@JsonProperty("settings") private Settings settings;
	@JsonProperty("users") private Users users;

	public RelUserSettings() {
	}

	public RelUserSettings(int id) {
		this.id = id;
	}

	public RelUserSettings(int id, Settings settings, Users users) {
		this.id = id;
		this.settings = settings;
		this.users = users;
	}

	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SQ_RELUSERSETTINGS")
	@SequenceGenerator(name = "SQ_RELUSERSETTINGS", sequenceName = "SQ_RELUSERSETTINGS", initialValue = 10, allocationSize = 1)
	@Id
	@Column(name="id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Fetch(FetchMode.JOIN)
	@BatchSize(size = 100)
	@ManyToOne(fetch=FetchType.EAGER, optional = true)
	@JoinColumn(name="settings_id")
	public Settings getSettings() {
		return this.settings;
	}

	public void setSettings(Settings settings) {
		this.settings = settings;
	}

	@Fetch(FetchMode.JOIN)
	@BatchSize(size = 100)
	@ManyToOne(fetch=FetchType.EAGER, optional = true)
	@JoinColumn(name="users_id")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}
// #SETTER_AND_GETTER
	
// ------------------ Logic part ------------------
	
	@PreRemove
	public void preRemove() {

	}
	
	public RelUserSettings init() {
		initList();
		initDicts();
		
		return this;
	}
	
	public RelUserSettings preInitList() {

		return this;
	}
	
	public RelUserSettings initList() {

		return this;
	}
	
	public RelUserSettings initDicts() {
		initSentity(getSettings());
		initSentity(getUsers());

		return this;
	}
	
	
}