/* #UPDATED */
/* #CLEARED */
package org.test.webcam.model.domain.entity;

// Generated 07.05.2015 16:26:32 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonProperty;

import javax.persistence.PreRemove;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.voodoodyne.jackson.jsog.JSOGGenerator;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.OptimisticLockType;
import org.hibernate.annotations.OptimisticLocking;
import org.hibernate.annotations.SelectBeforeUpdate;
import org.test.webcam.model.domain.SEntity;

import javax.persistence.CascadeType;

import java.util.LinkedList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;



/**
 * Settings generated by hbm2java, updated by voovee
 */
@DynamicInsert(true)
@DynamicUpdate(true)
@SelectBeforeUpdate(false)
@OptimisticLocking(type = OptimisticLockType.VERSION)
@JsonIdentityInfo(generator = JSOGGenerator.class)
@JsonIgnoreProperties({
			 
			  "firmid"
			, "firm"
			, "serieskey" 
})
@Entity
@Table(name="settings")
public class Settings extends SEntity  {

	private static final long serialVersionUID = 2239926533693631L;

	@JsonProperty("id") private Integer id;
	@JsonProperty("name") private String name;
	@JsonProperty("value") private String value;
	private List<RelUserSettings> relUserSettingses = new LinkedList<RelUserSettings>();

	public Settings() {
	}

	public Settings(int id) {
		this.id = id;
	}

	public Settings(int id,


			List<RelUserSettings> relUserSettingses) {
		this.id = id;
		this.name=name;
		this.value = value;
		this.relUserSettingses = relUserSettingses;
	}

	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SQ_SETTINGS")
	@SequenceGenerator(name = "SQ_SETTINGS", sequenceName = "SQ_SETTINGS", initialValue = 10, allocationSize = 1)
	@Id
	@Column(name="id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	

	@Column(name="name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name=name;
	}

	@Column(name="value")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	

	

	

	

	

	@OneToMany(fetch=FetchType.LAZY, cascade = { CascadeType.PERSIST, CascadeType.MERGE }, mappedBy="settings")
	public List<RelUserSettings> getRelUserSettingses() {
		return this.relUserSettingses;
	}

	public void setRelUserSettingses(List<RelUserSettings> relUserSettingses) {
		this.relUserSettingses = relUserSettingses;
	}
// #SETTER_AND_GETTER
	
// ------------------ Logic part ------------------
	
	@PreRemove
	public void preRemove() {

	}
	
	public Settings init() {
		initList();
		initDicts();
		
		return this;
	}
	
	public Settings preInitList() {
		for (RelUserSettings arg0 : getRelUserSettingses()) {
			arg0.setSettings(this);
		}


		return this;
	}
	
	public Settings initList() {
		initLists(relUserSettingses);

		return this;
	}
	
	public Settings initDicts() {

		return this;
	}
	
	
}