/* #UPDATED */
/* #CLEARED */
package org.test.webcam.model.domain.entity;

// Generated 07.05.2015 16:26:32 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonProperty;

import javax.persistence.PreRemove;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.voodoodyne.jackson.jsog.JSOGGenerator;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.OptimisticLockType;
import org.hibernate.annotations.OptimisticLocking;
import org.hibernate.annotations.SelectBeforeUpdate;
import org.test.webcam.model.domain.SEntity;

import java.util.LinkedList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;



/**
 * SizedPolytic generated by hbm2java, updated by voovee
 */
@DynamicInsert(true)
@DynamicUpdate(true)
@SelectBeforeUpdate(false)
@OptimisticLocking(type = OptimisticLockType.VERSION)
@JsonIdentityInfo(generator = JSOGGenerator.class)
@JsonIgnoreProperties({
			 
			  "firmid"
			, "firm"
			, "serieskey" 
})
@Entity
@Table(name="sized_polytic")
public class SizedPolytic extends SEntity  {

	private static final long serialVersionUID = 2253174836631154L;

	@JsonProperty("id") private Integer id;
	@JsonProperty("name") private String name;
	@JsonProperty("size") private Integer size;
	private List<PaymentPolytic> paymentPolytics = new LinkedList<PaymentPolytic>();

	public SizedPolytic() {
	}

	public SizedPolytic(int id) {
		this.id = id;
	}

	public SizedPolytic(int id,


			List<PaymentPolytic> paymentPolytics) {
		this.id = id;
		this.name=name;
		this.size = size;
		this.paymentPolytics = paymentPolytics;
	}

	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SQ_SIZEDPOLYTIC")
	@SequenceGenerator(name = "SQ_SIZEDPOLYTIC", sequenceName = "SQ_SIZEDPOLYTIC", initialValue = 10, allocationSize = 1)
	@Id
	@Column(name="id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	

	@Column(name="name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name=name;
	}

	@Column(name="size")
	public Integer getSize() {
		return this.size;
	}

	public void setSize(Integer size) {
		this.size = size;
	}

	

	

	

	

	

	@OneToMany(fetch=FetchType.LAZY, mappedBy="sizedPolytic")
	public List<PaymentPolytic> getPaymentPolytics() {
		return this.paymentPolytics;
	}

	public void setPaymentPolytics(List<PaymentPolytic> paymentPolytics) {
		this.paymentPolytics = paymentPolytics;
	}
// #SETTER_AND_GETTER
	
// ------------------ Logic part ------------------
	
	@PreRemove
	public void preRemove() {
		for (PaymentPolytic arg0 : getPaymentPolytics()) {
			arg0.setSizedPolytic(null);
		}


	}
	
	public SizedPolytic init() {
		initList();
		initDicts();
		
		return this;
	}
	
	public SizedPolytic preInitList() {
		for (PaymentPolytic arg0 : getPaymentPolytics()) {
			arg0.setSizedPolytic(this);
		}


		return this;
	}
	
	public SizedPolytic initList() {
		initLists(paymentPolytics);

		return this;
	}
	
	public SizedPolytic initDicts() {

		return this;
	}
	
	
}