/* #LAST_VIEW_OBJECT */
/* #UPDATED */
package org.test.webcam.model.domain.entity.view;

// Generated 07.05.2015 16:26:32 by Hibernate Tools 4.3.1

import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import javax.persistence.Table;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Column;

import org.test.webcam.model.domain.SView;


/**
 * RelUserSettingsView generated by hbm2java, updated by voovee
 */
@JsonIgnoreProperties({
			 
			  "firmid"
			, "firm"
			, "serieskey"
			, "settingsid"
			, "usersid" 
})
@Entity
@Table(name="rel_user_settings_view")
public class RelUserSettingsView extends SView  {

	private static final long serialVersionUID = 5568953553213556L;

	private Integer id;
	private String settings;
	private Integer settingsid;
	private String users;
	private Integer usersid;

	public RelUserSettingsView() {
	}

	public RelUserSettingsView(Integer id, String settings,
			Integer settingsid, String users, Integer usersid) {
		this.id = id;
		this.settings = settings;
		this.settingsid = settingsid;
		this.users = users;
		this.usersid = usersid;
	}

	@Id
	@Column(name="id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name="settings")
	public String getSettings() {
		return this.settings;
	}

	public void setSettings(String settings) {
		this.settings = settings;
	}

	@Column(name="settingsid")
	public Integer getSettingsid() {
		return this.settingsid;
	}

	public void setSettingsid(Integer settingsid) {
		this.settingsid = settingsid;
	}

	@Column(name="users")
	public String getUsers() {
		return this.users;
	}

	public void setUsers(String users) {
		this.users = users;
	}

	@Column(name="usersid")
	public Integer getUsersid() {
		return this.usersid;
	}

	public void setUsersid(Integer usersid) {
		this.usersid = usersid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RelUserSettingsView))
			return false;
		RelUserSettingsView castOther = (RelUserSettingsView) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getSettings() == castOther.getSettings()) || (this
						.getSettings() != null
						&& castOther.getSettings() != null && this
						.getSettings().equals(castOther.getSettings())))
				&& ((this.getSettingsid() == castOther.getSettingsid()) || (this
						.getSettingsid() != null
						&& castOther.getSettingsid() != null && this
						.getSettingsid().equals(castOther.getSettingsid())))
				&& ((this.getUsers() == castOther.getUsers()) || (this
						.getUsers() != null && castOther.getUsers() != null && this
						.getUsers().equals(castOther.getUsers())))
				&& ((this.getUsersid() == castOther.getUsersid()) || (this
						.getUsersid() != null && castOther.getUsersid() != null && this
						.getUsersid().equals(castOther.getUsersid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getSettings() == null ? 0 : this.getSettings().hashCode());
		result = 37
				* result
				+ (getSettingsid() == null ? 0 : this.getSettingsid()
						.hashCode());
		result = 37 * result
				+ (getUsers() == null ? 0 : this.getUsers().hashCode());
		result = 37 * result
				+ (getUsersid() == null ? 0 : this.getUsersid().hashCode());
		return result;
	}
// #SETTER_AND_GETTER
	
// ------------------ Logic part ------------------
	
	public RelUserSettingsView init() {
		initList();
		initDicts();
		
		return this;
	}
	
	public RelUserSettingsView customInitList(List<String> list) {
		
		return this;
	}
	
	public RelUserSettingsView initList() {

		return this;
	}
	
	public RelUserSettingsView initDicts() {
		return this;
	}
	
	
}