/* #LAST_VIEW_OBJECT */
/* #UPDATED */
package org.test.webcam.model.domain.entity.view;

// Generated 07.05.2015 16:26:32 by Hibernate Tools 4.3.1

import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.voodoodyne.jackson.jsog.JSOGGenerator;

import javax.persistence.Table;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.FetchType;

import java.util.List;
import java.util.LinkedList;
import java.util.Date;

import javax.persistence.Column;

import org.test.webcam.model.domain.SView;


/**
 * UsersView generated by hbm2java, updated by voovee
 */
@JsonIdentityInfo(generator = JSOGGenerator.class)
@JsonIgnoreProperties({
			 
			  "firmid"
			, "firm"
			, "serieskey"
			, "paymentpolyticid" 
})
@Entity
@Table(name="users_view")
public class UsersView extends SView  {

	private static final long serialVersionUID = 2293175457596876L;

	private Integer id;
	private Integer version;
	private String createdby;
	private Date createon;
	private Integer firm;
	private String lastmodifiedby;
	private Date modifyon;
	private String serieskey;
	private Boolean activated;
	private String activationkey;
	private String email;
	private Boolean enabled;
	private String firstname;
	private String landingpage;
	private String langkey;
	private String lastname;
	private String password;
	private String username;
	private String token;
	private String paymentpolytic;
	private Integer paymentpolyticid;

	private List<RelUserSettingsView> relUserSettingses = new LinkedList<RelUserSettingsView>();
	private List<UserRolesView> userRoleses = new LinkedList<UserRolesView>();
	
	public UsersView() {
	}

	public UsersView(Integer id, Integer version, String createdby,
			Date createon, Integer firm, String lastmodifiedby, Date modifyon,
			String serieskey, Boolean activated, String activationkey,
			String email, Boolean enabled, String firstname,
			String landingpage, String langkey, String lastname,
			String password, String username, String token,
			String paymentpolytic, Integer paymentpolyticid) {
		this.id = id;
		this.version = version;
		this.createdby = createdby;
		this.createon = createon;
		this.firm = firm;
		this.lastmodifiedby = lastmodifiedby;
		this.modifyon = modifyon;
		this.serieskey = serieskey;
		this.activated = activated;
		this.activationkey = activationkey;
		this.email = email;
		this.enabled = enabled;
		this.firstname=firstname;
		this.landingpage = landingpage;
		this.langkey = langkey;
		this.lastname=lastname;
		this.password = password;
		this.username=username;
		this.token = token;
		this.paymentpolytic = paymentpolytic;
		this.paymentpolyticid = paymentpolyticid;
	}

	@Id
	@Column(name="id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name="version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name="createdby")
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name="createon", length = 29)
	public Date getCreateon() {
		return this.createon;
	}

	public void setCreateon(Date createon) {
		this.createon = createon;
	}

	@Column(name="firm")
	public Integer getFirm() {
		return this.firm;
	}

	public void setFirm(Integer firm) {
		this.firm = firm;
	}

	@Column(name="lastmodifiedby")
	public String getLastmodifiedby() {
		return this.lastmodifiedby;
	}

	public void setLastmodifiedby(String lastmodifiedby) {
		this.lastmodifiedby = lastmodifiedby;
	}

	@Column(name="modifyon", length = 29)
	public Date getModifyon() {
		return this.modifyon;
	}

	public void setModifyon(Date modifyon) {
		this.modifyon = modifyon;
	}

	@Column(name="serieskey")
	public String getSerieskey() {
		return this.serieskey;
	}

	public void setSerieskey(String serieskey) {
		this.serieskey = serieskey;
	}

	@Column(name="activated")
	public Boolean getActivated() {
		return this.activated;
	}

	public void setActivated(Boolean activated) {
		this.activated = activated;
	}

	@JsonIgnore
	@Column(name="activationkey")
	public String getActivationkey() {
		return this.activationkey;
	}

	public void setActivationkey(String activationkey) {
		this.activationkey = activationkey;
	}

	@JsonIgnore
	@Column(name="email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name="enabled")
	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	@Column(name="firstname")
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname=firstname;
	}

	@Column(name="landingpage")
	public String getLandingpage() {
		return this.landingpage;
	}

	public void setLandingpage(String landingpage) {
		this.landingpage = landingpage;
	}

	@Column(name="langkey")
	public String getLangkey() {
		return this.langkey;
	}

	public void setLangkey(String langkey) {
		this.langkey = langkey;
	}

	@Column(name="lastname")
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname=lastname;
	}

	@JsonIgnore
	@Column(name="password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name="username")
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username=username;
	}

	@Column(name="token")
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	@Column(name="paymentpolytic")
	public String getPaymentpolytic() {
		return this.paymentpolytic;
	}

	public void setPaymentpolytic(String paymentpolytic) {
		this.paymentpolytic = paymentpolytic;
	}

	@Column(name="paymentpolyticid")
	public Integer getPaymentpolyticid() {
		return this.paymentpolyticid;
	}

	public void setPaymentpolyticid(Integer paymentpolyticid) {
		this.paymentpolyticid = paymentpolyticid;
	}

	 	@OneToMany(fetch=FetchType.LAZY)
	@JoinColumn(name="usersid")
	public List<RelUserSettingsView> getRelUserSettingses() {
		return this.relUserSettingses;
	}

	public void setRelUserSettingses(List<RelUserSettingsView> relUserSettingses) {
		this.relUserSettingses = relUserSettingses;
	}

	@OneToMany(fetch=FetchType.LAZY)
	@JoinColumn(name="usersid")
	public List<UserRolesView> getUserRoleses() {
		return this.userRoleses;
	}

	public void setUserRoleses(List<UserRolesView> userRoleses) {
		this.userRoleses = userRoleses;
	}

	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsersView))
			return false;
		UsersView castOther = (UsersView) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getVersion() == castOther.getVersion()) || (this
						.getVersion() != null && castOther.getVersion() != null && this
						.getVersion().equals(castOther.getVersion())))
				&& ((this.getCreatedby() == castOther.getCreatedby()) || (this
						.getCreatedby() != null
						&& castOther.getCreatedby() != null && this
						.getCreatedby().equals(castOther.getCreatedby())))
				&& ((this.getCreateon() == castOther.getCreateon()) || (this
						.getCreateon() != null
						&& castOther.getCreateon() != null && this
						.getCreateon().equals(castOther.getCreateon())))
				&& ((this.getFirm() == castOther.getFirm()) || (this.getFirm() != null
						&& castOther.getFirm() != null && this.getFirm()
						.equals(castOther.getFirm())))
				&& ((this.getLastmodifiedby() == castOther.getLastmodifiedby()) || (this
						.getLastmodifiedby() != null
						&& castOther.getLastmodifiedby() != null && this
						.getLastmodifiedby().equals(
								castOther.getLastmodifiedby())))
				&& ((this.getModifyon() == castOther.getModifyon()) || (this
						.getModifyon() != null
						&& castOther.getModifyon() != null && this
						.getModifyon().equals(castOther.getModifyon())))
				&& ((this.getSerieskey() == castOther.getSerieskey()) || (this
						.getSerieskey() != null
						&& castOther.getSerieskey() != null && this
						.getSerieskey().equals(castOther.getSerieskey())))
				&& ((this.getActivated() == castOther.getActivated()) || (this
						.getActivated() != null
						&& castOther.getActivated() != null && this
						.getActivated().equals(castOther.getActivated())))
				&& ((this.getActivationkey() == castOther.getActivationkey()) || (this
						.getActivationkey() != null
						&& castOther.getActivationkey() != null && this
						.getActivationkey()
						.equals(castOther.getActivationkey())))
				&& ((this.getEmail() == castOther.getEmail()) || (this
						.getEmail() != null && castOther.getEmail() != null && this
						.getEmail().equals(castOther.getEmail())))
				&& ((this.getEnabled() == castOther.getEnabled()) || (this
						.getEnabled() != null && castOther.getEnabled() != null && this
						.getEnabled().equals(castOther.getEnabled())))
				&& ((this.getFirstname() == castOther.getFirstname()) || (this
						.getFirstname() != null
						&& castOther.getFirstname() != null && this
						.getFirstname().equals(castOther.getFirstname())))
				&& ((this.getLandingpage() == castOther.getLandingpage()) || (this
						.getLandingpage() != null
						&& castOther.getLandingpage() != null && this
						.getLandingpage().equals(castOther.getLandingpage())))
				&& ((this.getLangkey() == castOther.getLangkey()) || (this
						.getLangkey() != null && castOther.getLangkey() != null && this
						.getLangkey().equals(castOther.getLangkey())))
				&& ((this.getLastname() == castOther.getLastname()) || (this
						.getLastname() != null
						&& castOther.getLastname() != null && this
						.getLastname().equals(castOther.getLastname())))
				&& ((this.getPassword() == castOther.getPassword()) || (this
						.getPassword() != null
						&& castOther.getPassword() != null && this
						.getPassword().equals(castOther.getPassword())))
				&& ((this.getUsername() == castOther.getUsername()) || (this
						.getUsername() != null
						&& castOther.getUsername() != null && this
						.getUsername().equals(castOther.getUsername())))
				&& ((this.getToken() == castOther.getToken()) || (this
						.getToken() != null && castOther.getToken() != null && this
						.getToken().equals(castOther.getToken())))
				&& ((this.getPaymentpolytic() == castOther.getPaymentpolytic()) || (this
						.getPaymentpolytic() != null
						&& castOther.getPaymentpolytic() != null && this
						.getPaymentpolytic().equals(
								castOther.getPaymentpolytic())))
				&& ((this.getPaymentpolyticid() == castOther
						.getPaymentpolyticid()) || (this.getPaymentpolyticid() != null
						&& castOther.getPaymentpolyticid() != null && this
						.getPaymentpolyticid().equals(
								castOther.getPaymentpolyticid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getVersion() == null ? 0 : this.getVersion().hashCode());
		result = 37 * result
				+ (getCreatedby() == null ? 0 : this.getCreatedby().hashCode());
		result = 37 * result
				+ (getCreateon() == null ? 0 : this.getCreateon().hashCode());
		result = 37 * result
				+ (getFirm() == null ? 0 : this.getFirm().hashCode());
		result = 37
				* result
				+ (getLastmodifiedby() == null ? 0 : this.getLastmodifiedby()
						.hashCode());
		result = 37 * result
				+ (getModifyon() == null ? 0 : this.getModifyon().hashCode());
		result = 37 * result
				+ (getSerieskey() == null ? 0 : this.getSerieskey().hashCode());
		result = 37 * result
				+ (getActivated() == null ? 0 : this.getActivated().hashCode());
		result = 37
				* result
				+ (getActivationkey() == null ? 0 : this.getActivationkey()
						.hashCode());
		result = 37 * result
				+ (getEmail() == null ? 0 : this.getEmail().hashCode());
		result = 37 * result
				+ (getEnabled() == null ? 0 : this.getEnabled().hashCode());
		result = 37 * result
				+ (getFirstname() == null ? 0 : this.getFirstname().hashCode());
		result = 37
				* result
				+ (getLandingpage() == null ? 0 : this.getLandingpage()
						.hashCode());
		result = 37 * result
				+ (getLangkey() == null ? 0 : this.getLangkey().hashCode());
		result = 37 * result
				+ (getLastname() == null ? 0 : this.getLastname().hashCode());
		result = 37 * result
				+ (getPassword() == null ? 0 : this.getPassword().hashCode());
		result = 37 * result
				+ (getUsername() == null ? 0 : this.getUsername().hashCode());
		result = 37 * result
				+ (getToken() == null ? 0 : this.getToken().hashCode());
		result = 37
				* result
				+ (getPaymentpolytic() == null ? 0 : this.getPaymentpolytic()
						.hashCode());
		result = 37
				* result
				+ (getPaymentpolyticid() == null ? 0 : this
						.getPaymentpolyticid().hashCode());
		return result;
	}
// #SETTER_AND_GETTER

	@Transient
	public String getLabel() {
		return lastname + " " + firstname; 
	}

	public void setLabel(String label) {
		
	}
	
	
// ------------------ Logic part ------------------
	
	public UsersView init() {
		initList();
		initDicts();
		
		return this;
	}
	
	public UsersView customInitList(List<String> list) {
		if (list.contains("relUserSettingses")) {
			initLists(relUserSettingses);
		}
		if (list.contains("userRoleses")) {
			initLists(userRoleses);
		}
		return this;
	}
	
	public UsersView initList() {
		initLists(relUserSettingses);
		initLists(userRoleses);

		return this;
	}
	
	public UsersView initDicts() {
		return this;
	}
	
	
}